### ISSUE TITLE
onnodig lange relatienamen volgens conventie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-common#20]
ik ben (achteraf) niet zo blij met de naamgevingsconventie in de design decisions op relaties:
> Relaties: De naam van de relatie plus de naam van de gerelateerde resource, tenzij er een reden is om dat niet te doen.

(ook al heb ik dit zelf eerder in een comment ingetypt: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/42#issuecomment-592520878)

Bijvoorbeeld een adres heeft een property woonplaats en ook een link naar de resource woonplaats. Waarom moet dat dan ligtInWoonplaats zijn? Had het property dan ook ligtInWoonPlaatsNaam moeten heten?

Bijvoorbeeld bij een zakelijk recht horen een aantal stukken. Moeten de relaties daarnaartoe dan in isGebaseerdOpStukken en isVermeldInStukken? Tot nu toe is volstaan met de relatie stukken.

We nemen meestal relaties op twee mogelijke manieren op:
- de identificatie van de gerelateerde resource. Bijvoorbeeld "openbareRuimteIdentificatie"
- een HAL link naar de gerelateerde resource. 

Deze naamgevingsconventie zegt niet expliciet over welke vorm van relatie opnemen we het hebben. Ik neem aan dat bedoeld wordt relaties in HAL links.

Mijn bezwaren:
1. hiermee committeren we ons aan een directe koppeling met de relatie en elementnaam uit (een versie van) een informatiemodel
2. propertynamen worden onnodig lang. Bijvoorbeeld een relatie van een persoon naar diens adres is duidelijk genoeg met "adres". Relatienaam "verblijftOpAdres" is niet duidelijker. 
Soms is de naam van de resource duidelijker en voldoende (bijvoorbeeld "woonplaats" voor de ligt in relatie van een adres naar de woonplaats-resource), soms is de naam van de relatie duidelijker (bijvoorbeeld een persoon heeft relaties naar ouders, partners en kinderen die allemaal personen zijn), dan zijn de naam van alleen de resource of alleen de relatie niet duidelijk of ambigu, zodat je beide moet gebruiken.
3. HAL-links zijn bedoeld om de gebruiker te helpen, dus voor discoverability. Het is niet bedoeld om relaties aan te duiden, maar deze naamgevingsconventie suggereert dit wel met het aanduiden van HAL links als relaties en het "dwingen" om deze naar de relatie te benoemen.

**Comment by MelvLee** [comment]
Bij de BRP kennen we woonadres en briefadres (als enum). Ik denk dat het ook handig is om zoveel mogelijk dezelfde naamgeving over domeinen heen te gebruiken

**Comment by fsamwel** [comment]
@MelvLee 
> Bij de BRP kennen we woonadres en briefadres (als enum). Ik denk dat het ook handig is om zoveel mogelijk dezelfde naamgeving over domeinen heen te gebruiken

Hoe bedoel je dit? Dit onderscheid bestaat niet in andere domeinen. Een correspondentieadres is iets anders dan een briefadres

**Comment by MelvLee** [comment]
Ik dacht dat met correspondentieadres en briefadres hetzelfde werd bedoeld. Ik neem aan dat woonAdres en verblijftOpAdres wel hetzelfde wordt bedoeld, toch?

**Comment by JohanBoer** [comment]
Dit is een beetje een dilemma. Als we de HAL-links inderdaad alleen maar beschouwen als "handig hulpmiddeltje" voor consumers, dan moet je daar, zeker in het geval van templated resources, misschien alleen maar de naam van de gerelateerde resource in gebruiken. 

De betekenis van de relaties zou je dan opnemen in de property waarin je de identificatie van die resource opneemt (die je gebruikt in de Hallink). Dat zou dus betekenen dat je bijvoorbeeld bij een Adresseerbaarobject de properties een isHoofdadres en een isNevenadres opneemt (met daarin de identificaties naar de betreffende adressen) en in de Hallinks alleen maar een link naar de resource Adres. 

Dat betekent dat we voor de Hallinks een andere naamgevingsconventie (Resourcenaam) toepassen dan voor de property waar de de identificatie van de gerelateerde resource in opnemen (relatienaam + resourcenaam) 

> Bijvoorbeeld een adres heeft een property woonplaats en ook een link naar de resource woonplaats. Waarom moet dat dan ligtInWoonplaats zijn? Had het property dan ook ligtInWoonPlaatsNaam moeten heten?

Geen goed voorbeeld. Deze property in adres zou woonplaatsNaam moeten zijn. Dit is namelijk in het adres niet de identificatie naar het object woonplaats toe, maar de woonplaatsnaam zoals je die in een adres wilt zien. De relatie zou daarnaast dan opgenomen moet worden door bv woonplaatsIdentificatie op te nemen, of (volgens de conventie) ligtInWoonplaats. EN vervolgens een Hallink met de naam Woonplaatsen.

> Bijvoorbeeld bij een zakelijk recht horen een aantal stukken. Moeten de relaties daarnaartoe dan in isGebaseerdOpStukken en isVermeldInStukken? Tot nu toe is volstaan met de relatie stukken.

Het toevoegen van de betekenis van de relatie kan relevant zijn. Denk aan hoofdadres en nevenadressen. Allebei links naar adressen, maar wel met verschillende betekenis. Hetzelfde geldt inderdaad voor stukken. Door isVermeldIn en isGebaseerdOp weg te laten schuif je deze twee semantisch verschillende relaties op 1 hoop of negeer je 1 van de 2 relaties (wat je ook zou moeten documenteren.  

> 1. hiermee committeren we ons aan een directe koppeling met de relatie en elementnaam uit (een versie van) een informatiemodel

Dat zou je niet moeten doen. Je commiteert je aan de relatie van een resource met een andere resource.  Dus ligtInWoonplaats en niet in ligtinWoonlaatsIdentificatie.

> propertynamen worden onnodig lang. Bijvoorbeeld een relatie van een persoon naar diens adres is duidelijk genoeg met "adres". Relatienaam "verblijftOpAdres" is niet duidelijker.

Deze toevoeging is wel van belang als de betreffende persoon bijvoorbeeld ook een correspondentieAdres zou hebben.  

Je kan ervoor kiezen om de relatienaam alleen toe te voegen op het moment dat er 2 relaties naar dezelfde resource zijn. Nadeel daarvan is dat als je dit later wilt doen er dan een breaking change ontstaat Bv. Als we nu adres opnemen als property-naam en we voegen in de volgende versie correspondentieAdres toe, dan is die toevoeging niet brekend, maar moeten we ook Adres omnoemen naar verblijfAdres en dat is wel brekend. 


Best wel een lange reactie geworden. Misschien goed om deze te agenderen voor een ontwerpsessie.
