### ISSUE TITLE
Voorstel tot correcties op design_decisions.md

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-common#28]
Bij de review van pull request #26 heb ik een aantal verbetermogelijkheden geconstateerd:

DD1.12 Redundantie in propertynamen weghalen. Dit is het geval wanneer in een propertynaam de gegevensgroepnaam of resourcenaam wordt herhaald waar die in zit.

DD2.1 voorvoegseltabel is geen voorbeeld van een referentielijst met code en waarde.

DD2.1 (90) "Als landelijk beheerde dynamische domeinwaarden ook daadwerkelijk landelijk beschikbaar gesteld worden (zoals de common ground gedachte wel beoogd) dan worden deze als resource ontsloten en dus als link (uri) opgenomen.": dit suggereert dat in dat geval de code en omschrijving niet meer worden meegeleverd en alleen een link. dat is erg onvriendelijk voor de gebruiker. het toevoegen van de link naast de code en omschrijving is dan wel een goed idee, hoewel de toegevoegde waarde erg beperkt is. het volgen van die link geeft namelijk nauwelijks extra informatie. hoogstens sinds wanneer de code in gebruik is. Graag verwijderen.

DD2.2 "wordt altijd de *code* van de entry gebruikt": hier "altijd" verwijderen

DD2.3 "Enumeraties worden in het bericht opgenomen als waarde": Moet worden: "We gebruiken als enumeratiewaarden betekenisvolle waarden. Dus niet M en V, maar man en vrouw."
Regel 96 t/m 100 (toelichting en ratio bij DD2.3) graag verwijderen, deze klopt niet. Want:
	- De reden om een enumeratie op te nemen is omdat het een computerleesbare code moet zijn, niet om deze te tonen aan een persoon (daarvoor kan het ook een normale string zijn). Het is en blijft een code.
	- In code wordt een enumeratiewaarde een constante. Je wil in code geen heel lange constantenamen. Enumeratiewaarden zijn regelmatig heel lang.
	- In applicaties zal normaal gesproken nooit een enumeratiewaarde direct getoond worden aan een eindgebruiker en het hoeft dus ook niet voor een eindgebruiker vriendelijk leesbaar te zijn.
	Dat geldt zelfs al voor codes voor geslacht als "man" en "vrouw". In een implementatie kan dat gebruikt worden om "meneer" en "mevrouw" te tonen, of "hij" en "zij".
	- de ratio is dus dat een developer in zijn code moet begrijpen wat de code betekent, om fouten in de implementatie te voorkomen.

DD3.1 Graag verwijderen. Voegt niks toe. Kan hoogstens een opmerking zijn bij DD3.2.

DD3.4 Graag verwijderen. Deze is achterhaald (geldt alleen voor BRP API).

DD4.2 Graag verwijderen. Zo hebben we dat nergens in de HC API's gedaan. We gebruiken functionele datums wanneer die bestaan. En voor einddatums nemen we in de naam op of het een datum tot is of een datum tot en met.

DD4.1 en DD4.3 Vraag ik me af of dit algemene Haal Centraal richtlijnen zijn. Zo hebben we dat gedaan voor BRP. Maar moet dit altijd zo?

DD5.1 Hier moeten we nog over spreken. De beschreven manier toont de descriptions niet in Swagger en het komt ook niet door als comment in gegenereerde code. Ik pleit ervoor het zo op te nemen dat descriptions wel doorkomen in zowel Swagger als gegenereerde code.

DD5.3 Graag algemenere beschrijving: De technische definitie van properties alleen opnemen voor zover noodzakelijk voor gebruik.
Meestal is definitie van properties in de response voldoende met propertynaam, type, format, description en example. 
We gebruiken niet pattern, minimum, maximum, minLength, maxLength, minItems, required, tenzij....
Title gebruiken we alleen wanneer de propertynaam afwijkt van de naam in het informatiemodel (en het informatiemodel bekend is bij veel gebruikers).
Enum gebruiken we wanneer (sommige/mogelijke) gebruikers de mogelijke waarden gebruiken in code/algoritmes en daarom moeten weten welke mogelijke waarden er zijn.

DD5.5 Dit is een architectuurprincipe voor HC. Kan veel algemener worden beschreven. We nemen in de API alleen gegevens op die zijn vastgelegd in de bronregistratie van de provider van de API. Een van de consequenties daarvan is DD3.2 het niet embedded van resources uit een andere registratie. Een andere consequentie is het niet opnemen van kerngegevens. Dus de regel is halen bij de bron, een consequentie (toelichting of voorbeeld) is het niet opnemen van gemeentelijke kerngegevens en plusgegevens.

DD5.8 Deze graag verwijderen. Dit impliceert namelijk dat de API specificaties worden ontworpen vanuit het informatiemodel. Zo doen we dat niet. De API wordt ontworpen vanuit  user stories, niet vanuit een informatiemodel. Dát moet de ontwerprichtlijn zijn. Hoe dat in een informatiemodel gemodelleerd is, is totaal niet relevant. We gebruiken een gegevenswoordeboek (bij BRK en BAG in de vorm van een informatiemodel, bij BRP in de vorm van het logisch ontwerp) om namen en betekenissen van gebruikte gegevens (properties en soms resources) te kennen en gebruiken.

DD5.11 Deze kan denk ik verwijderd worden. Dit is toch hetzelfde als DD5.10?
Verder graag geen term "indicator" of "attribuut" gebruiken wanneer je "property" bedoelt. We gebruiken JSON(-schema), niet UML. Dus moeten ook JSON termen worden gebruikt: "object", "property" en "array".

**Comment by melsk-r** [comment]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-common/pull/30

> DD4.1 en DD4.3 Vraag ik me af of dit algemene Haal Centraal richtlijnen zijn. Zo hebben we dat gedaan voor BRP. 

Hierover moet je denk ik even met Johan discussiëren. Ik heb beide regels even gelaten voor wat ze zijn.

DD5.1: De beschrijving heb ik aangepast n.a.v. de bespreking vanochtend.

Kan de ratio in DD5.5 wel blijven staan?

**Comment by fsamwel** [comment]
> Hierover moet je denk ik even met Johan discussiëren. Ik heb beide regels even gelaten voor wat ze zijn.

Goed idee. Het is ook niet erg dat deze richtlijnen blijven staan, ik vermoed dat deze ook voor andere Haal Centraal API's gebruikt kunnen worden.

> Kan de ratio in DD5.5 wel blijven staan?

Naar mijn idee niet. Je moet niet eens bedenken dat je die plusgegevens in de API op zou willen nemen. Wanneer je een BRP API maakt, zitten daar BRP gegevens in, niks anders. 

De ratio is dat het opnemen van gegevens uit een andere bron zorgt voor tight coupling met die andere bron. 
Ook kan een bronsysteem niet zomaar gegevens uit een andere bron halen, zeker niet wanneer dat gegevens zijn waar autorisaties voor nodig zijn (zoals privacy gevoelige gegevens).
Het is bovendien al genoeg uitdaging te zorgen dat een bron zijn eigen gegevens op de gewenste manier ontsluit. Daar wil je niet aan toevoegen dat het Kadaster gegevens van het RvIG of KvK ook nog ontsluit.

**Comment by melsk-r** [comment]
Ik kan me vinden in je argumentatie m.b.t. de ratio en ik heb hem daarom aangepast.

**Comment by melsk-r** [comment]
Volgens mij is deze afgewerkt, zijn de wijzigingen ook al gemerged met de master en kan hij gesloten worden.
Correct me if I'm wrong!
