### ISSUE TITLE
Geen validatie, reason en code voor foutieve coördinaten invoer

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-common#51]
Als er met een locatie query parameter gezocht wordt, dan bestaat deze locatie uit coördinaten (x, y[, z]). Als er voor een coördinaat een waarde wordt ingevoerd die ongeldig is bv. 'abc' dan is hier geen passende foutmelding voor gedefinieerd in de foutafhandeling.feature beschrijving. Kan deze worden toegevoegd?
Bv.
https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=a,b

**Comment by fsamwel** [comment]
wanneer er maar 1 waarde wordt teruggegeven, zoals bij locatie=12345.67, dan moet een minItems fout worden gegeven.
wanneer een waarde geen decimaal getal (number) is, moet een Number fout gegeven worden. Voor dit laatste heb ik pull request #52 ingediend om dit toe te voegen.
