### ISSUE TITLE
Welke foutmelding bij geen path parameter

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-common#54]
Als we er vanuit gaan dat met zoekparameter een query parameter wordt bedoeld.In de foutafhandeling feature beschrijving, dan  staat er op dit moment niet een scenario beschreven voor de situatie waarbij geen path parameter wordt opgegeven. De beschrijving bij het eerste scenario voldoet niet voor de situatie dat er geen path parameter wordt meegegeven. De beschrijving bij het derde scenario waarbij met een zoekparameter wordt gezocht voldoet niet voor een path parameter.

Kan de feature beschrijving worden aangepast zodat duidelijk wordt hoe de foutmelding eruit moet zien, in het geval er geen path parameter wordt meegegeven. 

Voorstel is om het volgende terug te geven:

| Foutsituatie                       | status | title                                                         | code              |
| Geen parameter is meegegeven | 400 | Ten minste één parameter moet worden opgegeven. | paramsRequired

| validatie        | reason                                                    | code         |
| required | Parameter is verplicht. | required |

**Comment by JohanBoer** [comment]
Volgens mij wordt er bij het ontbreken van de pathparameter een 404 teruggegeven. En dat alleen als je de conclusie kan trekken dat het de path-parameter is die ontbreekt.

Als een request wordt verstuurd dat er als volgt uitziet : https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen , dan weet je als provider niet of de consumer de path-prameter, de zoek-parameter of de query-parameter(s) vergeten is. Dan is een 400 een juiste respons volgens mij.

Echter als de volgende request wordt verstuur : https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/nummeraanduidingen
dan is volgens mij een 404 op zijn plaats, want dit endpoint bestaat niet.

**Comment by strijm** [comment]
OK dan sturen we een 404 als een path parameter ontbreekt.

**Comment by strijm** [comment]
Moet dit dan nog in de feature beschrijving worden aangepast?

**Comment by JohanBoer** [comment]
> Moet dit dan nog in de feature beschrijving worden aangepast?

Volgens mij niet. 

Bij een endpoint waarbij aan het eind een pathparameter voor kan komen, maar waarbij ook query-parameters kunnen worden toegevoegd geef je bij het ontbreken van de pathparameter een fout op vanwege :
 | Verplichte parameter(combinatie)   | 400    | Minimale combinatie van parameters moet worden opgegeven.     | paramsCombination |

Bij een endpoint dat alleen maar bestaat met een path-parameter geef je een fout op vanwege : 
  | Opgevraagde resource bestaat niet  | 404    | Opgevraagde resource bestaat niet.                            | notFound          |

**Comment by fsamwel** [comment]
/adressen geeft 400 fout "Ten minste één parameter moet worden opgegeven."
/adressen/ geeft 404 fout

**Comment by strijm** [comment]
Bij ontbreken van pad parameter 404 fout teruggeven. Bij fouten m.b.t. query parameters 400 fouten teruggeven.
