### ISSUE TITLE
Fields parameter i.cm. templated links issue

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-common#55]
Uit de uri-templating feature lees ik dat als er met een fields parameter op _links wordt gefilterd maar niet op de property (array) die identificaties bevat die ingevuld kunnen worden in een templated link. De lijst altijd geleverd moet worden. 

Mijn conclusie is dan, dat er altijd maar één link is en dat het dus niet nodig is om een array van links te hebben.

Bv. de BAG panden links ziet er nu als volgt uit:

    Pand_links:
      type: object
      properties:
        self:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink'
        adressen:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink'
        adresseerbareObjecten:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink'

Maar doordat er gebruik wordt gemaakt van URI templates, is er maar één link nodig, dus hoeft er onder adressen en adresserbareObjecten geen array maar één enkele link te staan. Als dit het geval is, moet dan de BAG OAS specificatie hierop aangepast worden?

**Comment by fsamwel** [comment]
het idee is dat je als provider HAL links levert en zelf kan bepalen of je die templated levert of niet. De keuze daarvoor wordt bijvoorbeeld bepaald door het aan tal links dat je moet leveren. Bijvoorbeeld een pand met heel veel adressen (flatgebouw) zou je alle nummeraanduidingIdentificaties moeten opnemen en evenveel _links.adressen. Dan kan je ervoor kiezen deze templated aan te bieden. 
Door deze link te definiëren als enkele link i.p.v. array wordt je verplicht het templated aan te bieden en kan je niet meer kiezen het nu of in de toekomst als gewone link aan te bieden.
De gekozen constructie biedt dus het meeste flexibiliteit voor de aanbieder.

De feature die je noemt zegt dus ook niet dat je dit soort links templates moet aanbieden, maar dat wanneer je een link templated aanbiedt, je bij gebruik van fields de link en de gebruikte identificatie-property aan elkaar moet koppelen.
