### ISSUE TITLE
Toevoeging aan Design decisions n.a.v. BAG#234

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-common#73]
HaalCentraal BAG issue [234](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/234) gaat over de wijze van definiëren van url's voor interne links. Dit kan met absolute urls maar in het issue wordt aangegeven dat relatieve url's de voorkeur hebben.

Ik vraag me af of dit niet ergens in de Design Decision moet landen.
Overigens gaat het hier n.m.m. niet echt om een Design Decision en is het dus de vraag waar het na invoering van #27 moet worden ondergebracht.

**Comment by fsamwel** [comment]
ja (misschien), als het echt design decisions waren geweest. Nu is het een ontwerprichtlijnen document, gericht op de API ontwerper(s). Dus zou ik het nu eerder in een feature verwachten.

**Comment by melsk-r** [comment]
Begrijp ik maar is het niet goed om API ontwerpers voor te houden dat dit een optie is om in overweging te nemen?

**Comment by fsamwel** [comment]
we gebruiken HAL-links. In de API specificaties wordt niet voorgeschreven of het absolute of relatieve links zijn, dus is er wat dat betreft niet zoveel te overwegen.

**Comment by JohanBoer** [comment]
Dus is dit een implementatie-issue en geen design-issue.

**Comment by melsk-r** [comment]
Akkoord om hem niet op te nemen in de Design Decisions.
We gaan hem in de [API Kennisbank](https://github.com/VNG-Realisatie/API-Kennisbank) echter wel opnemen als Implementatie overweging in een apart daarvoor te creëren document.
