### ISSUE TITLE
Herformuleren DD1.17

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-common#84]
Ik ben niet zo blij met DD1.17. Staat er nu zo dat het verplicht (sterk aanbevolen) is title toe te voegen wanneer er een afwijking is. 

> ### DD1.17 Maak gebruik van 'title' (en alleen dan) indien wordt afgeweken van de naam van het corresponderende gegeven in het gegevenswoordenboek
> Wanneer er in de naam van een property wordt afgeweken (anders dan toepassen lowerCamelCase, UpperCamelCase en snakeCase) van de naam van het corresponderende gegeven in het gegevenswoordenboek, wordt de naam van dat gegeven in het gegevenswoordenboek opgenomen. Daarbij wordt gebruik gemaakt van het attribuut 'title' in de definitie van het property in de API. In alle andere gevallen wordt 'title' niet opgenomen in de definitie van een property.

Ik denk dat title alleen nodig is wanneer dit begrip in het gegevenswoordenboek voor een bepaalde doelgroep een erg bekend begrip is, en de gekozen naar van het gegeven daar zoveel van afwijkt dat verwijzing naar het andere begrip nodig is. Enig voorbeeld in de Haal Centraal API's tot nu toe dat ik me voor de geest kan halen is geheimhoudingPersoonsgegevens - indicatie geheim.
Andere afwijkingen ("straatnaam" wordt "straat"), zoals inkorten, uitschrijven van een afkorting, enz. maakt de title niet nodig.
In essentie moet gebruik van title dus een grote uitzondering zijn, want waarom zou je zo ver afwijken van het begrip in het gegevenswoordenboek, wanneer dit begrip voor veel gebruikers wel bekend is...

Ik stel de volgende formulering voor:

> ### DD1.17 Maak alleen gebruik van 'title' indien wordt afgeweken van de naam van het corresponderende gegeven in het gegevenswoordenboek
> Wanneer er in de naam van een property vergaand wordt afgeweken (anders dan toepassen lowerCamelCase, UpperCamelCase en snakeCase, inkorten, uitschrijven afkorting, enz.) van de naam van het corresponderende gegeven in het gegevenswoordenboek, en vermoed wordt dat dit voor sommige gebruikers verwarring kan veroorzaken, wordt de naam van dat gegeven in het gegevenswoordenboek opgenomen in attribuut 'title' van de property definitie. In alle andere gevallen wordt 'title' niet opgenomen in de definitie van een property.
> In deze situaties is het eerst verstandig om de afwijkende naamgeving voor het property nog eens te overwegen.

N.B. mijn voorgestelde zin is zo lang geworden dat waarschijnlijk niemand het meer snapt. Suggesties om dat anders te doen?

**Comment by melsk-r** [comment]
Inmiddels doorgevoerd.
